version: '3.5'
services:
  sse-db:
    image: postgres:12
    expose:
      - "5432"
    networks:
      - asclepios
    volumes:
      - ./data/sse-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SSE_SERVER_DB_USER}
      POSTGRES_PASSWORD: ${SSE_SERVER_DB_PASSWORD}
      POSTGRES_DB: ${SSE_SERVER_DB_NAME}
      PGDATA: /var/lib/postgresql/data

  sse:
    image: uowcpc/asclepios-server:dev
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    networks:
      - asclepios
    depends_on:
      - sse-db
    environment:
      DJANGO_LOGLEVEL: ${SSE_SERVER_DJANGO_LOGLEVEL}
      TA_SERVER: ${SSE_SERVER_TA_SERVER}
      DB_NAME: ${SSE_SERVER_DB_NAME}
      DB_USER: ${SSE_SERVER_DB_USER}
      DB_PASSWORD: ${SSE_SERVER_DB_PASSWORD}
      DB_HOST: ${SSE_SERVER_DB_HOST}
      DB_PORT: ${SSE_SERVER_DB_PORT}
      ALLOWED_HOSTS: ${SSE_SERVER_ALLOWED_HOSTS}
      DJANGO_DEBUG: ${SSE_SERVER_DJANGO_DEBUG}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_URL: ${MINIO_URL}
      MINIO_SSL_SECURE: ${MINIO_SSL_SECURE}
      MINIO_EXPIRE_GET: ${MINIO_EXPIRE_GET}
      MINIO_EXPIRE_PUT: ${MINIO_EXPIRE_PUT}

  ta-db:
    image: postgres:12
    expose:
      - "5432"
    networks:
      - asclepios
    volumes:
      - ./data/ta-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TA_DB_USER}
      POSTGRES_PASSWORD: ${TA_DB_PASSWORD}
      POSTGRES_DB: ${TA_DB_NAME}
      PGDATA: /var/lib/postgresql/data

  ta:
    image: uowcpc/asclepios-ta:0.3
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    networks:
      - asclepios
    depends_on:
      - ta-db
    # entrypoint: gunicorn TA.wsgi:application --name TA --bind 0.0.0.0:8000 --workers 3 --limit-request-line 0
    environment:
      DJANGO_LOGLEVEL: ${TA_DJANGO_LOGLEVEL}
      DB_NAME: ${TA_DB_NAME}
      DB_USER: ${TA_DB_USER}
      DB_PASSWORD: ${TA_DB_PASSWORD}
      DB_HOST: ${TA_DB_HOST}
      DB_PORT: ${TA_DB_PORT}
      ALLOWED_HOSTS: ${TA_ALLOWED_HOSTS}
      HASH_LENGTH: ${TA_HASH_LENGTH}
      KEY_G: ${TA_KEY_G}
      SALT: ${TA_SALT}
      IV: ${TA_IV}
      DJANGO_DEBUG: ${TA_DJANGO_DEBUG}

  # sse-client:
  #   image: uowcpc/asclepios-client:0.4
  #   ports:
  #     - "3000:80"
  #   expose:
  #     - "80"
  #   networks:
  #     - asclepios
  #   depends_on:
  #     - sse
  #     - ta
  #   environment:
  #     ALLOWED_HOSTS: ${SSE_CLIENT_ALLOWED_HOSTS}
  #     DJANGO_DEBUG: ${SSE_CLIENT_DJANGO_DEBUG}

  # pdp:
  #   image: asclepios/abac-authorization-server
  #   expose:
  #     - "7071"
  #   networks:
  #     - asclepios
  #   volumes:
  #     - ./data/abac-server/config:/abac-server/config
  #     - ./data/abac-server/policies:/abac-server/policies
  #   environment:
  #     AUTH_SERVER_URL: "http://keycloak:8080/auth"
    
  minio:
    image: minio/minio
    volumes:
      - ./data/minio:/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
    networks:
      - asclepios
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data/minio
  
networks:
 asclepios:
  driver: bridge
  name: asclepios

# volumes:
#   sse-db-data:
#   ta-db-data:
